### ISSUE TITLE
Display viewer on file component show pages

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/nta-arclight#105]
For components that have a digital object associated with them, we want to display a viewer on the component show page for the user to view the digital content directly, rather than making them follow an external link to view the content outside of the NTA application. 

I believe we have three distinct, mutually-exclusive types of components in NTA:

- Collection - The top level object, which has unique type of metadata (EAD frontmatter stuff, Access info). 
- Containers - Objects Lauren is creating for purposes of creating an intellectual organization of the content inventory, such as the series and sub-series objects. These component pages have a "Contents" section but never (in NTA, though this won't necessarily always be true for other collections) a digital object directly associated with them.
- Files - Objects that are contained within a series/sub-series parent(s). In NTA I believe these always have one and only one digital object associated with them.

For the file component objects, instead of the "Contents" section we show for container components, we want to show a "Digital content" section. If I'm understanding things correctly, there will be two variations of this, depending on whether the component's digital object is a PDF or media (audio or video). The page should basically be the same for both variations, just the type of viewer (Mirador versus the media player) we load will be different.

## Example - File with a PDF object associated with it

<img width="686" alt="Screen Shot 2022-10-27 at 3 49 24 PM" src="https://user-images.githubusercontent.com/101482/198414830-a5593435-656a-4dd7-aa7b-15d9a2ef0533.png">

---

- **A:** Object metadata - not relevant for this ticket
- **B:** Section heading - `Digital content` as an `<h2 class="al-show-sub-heading">`, which is what the equivalent "Contents" section for a container component is coded as. (I think with that class it currently won't look like the mockup (it will be uppercased) but we can address that later; I just want the headings to have the same class so we can update the style consistently later as part of a larger visual design update.)
- **C:** Viewer - whichever of the two viewers is appropriate for the digital object
- **D**: Access section - not relevant for this ticket (I think ultimately we won't need this section for NTA components because they won't have item-level access statements) but included for placement context because that section currently appears on our pages.

## Example - File with a media object associated with it
Nothing different other than the type of viewer used:

<img width="675" alt="Screen Shot 2022-10-27 at 3 53 48 PM" src="https://user-images.githubusercontent.com/101482/198415698-a07d6a39-9235-4d94-94f8-40fbda6cac5b.png">

**Comment by jcoyne** [comment]
@ggeisler the viewer is now available on stage.  Previously there was a bug that was preventing it from being show.  If there are additional changes that are needed, should they be done in Arclight?


Here's what I see on stage:


![Image](https://user-images.githubusercontent.com/92044/199060150-d5b0b119-1a07-4486-9169-be145057449e.png)


It looks like you want the header chagned from "ONLINE ACCESS" to "Digital Content", is that right?

**Comment by ggeisler** [comment]
@jcoyne 

> If there are additional changes that are needed, should they be done in Arclight?

I don't think there are any additional changes needed, other than the header, which I think we should do in NTA.

> It looks like you want the header chagned from "ONLINE ACCESS" to "Digital Content", is that right?

Yep, for NTA I think that's how we want to refer to it.

**Comment by thatbudakguy** [comment]
Closing since the text has now been changed — arclight forces some of these headings to all-caps ("DIGITAL CONTENT"), but I think we can address that in a later PR since we'll probably want to do it for other headings on the page too.

**Comment by thatbudakguy** [comment]
actually, https://github.com/projectblacklight/arclight/pull/1248/files should resolve the all-caps heading display too.
