### ISSUE TITLE
Omit the Request button in the Collection info box

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/nta-arclight#113]
I'm assigning this to @laurensorensen first so she can confirm (or tell me my assumption is incorrect) that we shouldn't show the Request button in the Collection info box because there is nothing to request with this collection. I'm assuming that everything in it will be available online through the site and we have no physical objects associated with the collection to request:

<img width="380" alt="Screen Shot 2022-10-28 at 2 02 26 PM" src="https://user-images.githubusercontent.com/101482/198733047-0ee08a37-2278-4f71-b03e-a27063eeabf6.png">

---

If you agree, Lauren, you could just leave a comment to that effect and unassign yourself and this would be ready for a dev fix to remove/hide the button.

**Comment by laurensorensen** [comment]
Correct! Thanks Gary
