### ISSUE TITLE
How to handle the component-level access statement?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/nta-arclight#119]
We definitely want an access statement for the NTA collection. I think the discussion in #92 suggests this is a planned update to the EAD. However, we need to decide how to handle the the access statement that is displayed for components within the collection.

At the end of the component show page, ArcLight displays an Access section that includes any specific access restrictions that apply to that component (and then repeats some of the repository info from the collection-level access statement). For example, certain items in a collection can have more restrictive access than the collection as a whole, so this is a useful arrangement.

For the NTA collection, however, my assumption is that all items in the collection share the same access info as the collection as a whole. If that's true, there would be no additional info provided by the component-level access statement we now display:

<img width="848" alt="Screen Shot 2022-10-31 at 10 43 50 AM" src="https://user-images.githubusercontent.com/101482/199078799-46638cec-3423-46c3-88f7-09dc52d92168.png">

---

From a visual design perspective, I'd therefore lean towards omitting the entire Access section on component-level pages, and relying on the collection-level Access section for the access and repository info. This would enable the component show page to feel less visually cluttered and make it easier for the user to focus on the item metadata and viewer or metadata and contents (for parent components), which is the only unique info on the page.

For now this is a question for @laurensorensen. If she agrees I can make another more development-oriented ticket about the suggested solution.

**Comment by marlo-longley** [comment]
Just linking this for technical reference https://github.com/sul-dlss/nta-arclight/issues/92

**Comment by laurensorensen** [comment]
Agree with @ggeisler: "omitting the entire Access section on component-level pages, and relying on the collection-level Access section for the access and repository info."

**Comment by ggeisler** [comment]
Closing; created more actionable ticket #124.
