### ISSUE TITLE
Confirm URLs and server names; contact Ops about change

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#123]
This raises the question, should we leave all the server names as nta-*, when the URLs will be changing to virtualtribunals?

**Comment by marlo-longley** [comment]
The ticket for Ops:

- change domains to replace nta-* with virtualtribunals-* for stage and prod - https://nta-stage.stanford.edu becomes https://virtualtribunals-stage.stanford.edu

- If possible also change the host names for servers from nta to vt

**Comment by thatbudakguy** [comment]
ops-tasks ticket: https://github.com/sul-dlss/operations-tasks/issues/3214
