### ISSUE TITLE
Omit the Access section on component show pages

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/nta-arclight#124]
As described in #119, all NTA components have the same access status as the collection as a whole. The current component show page Access section below the viewer therefore doesn't add anything new to the access section available as part of the collection frontmatter metadata page. Acknowledging this might very occasionally make a user look a bit harder for access-related information, overall it seems reasonable to:

- [x] Omit the display of the Access section on component-level show pages.
- [ ] Continue to display the Access section that is part of the collection-level display.

(As with many of the decisions to "omit" parts of the NTA's ArcLight UI, we might want to re-enable the current default behavior in the future, if and when we add other collections to the NTA ArcLight instance and they do have variable access restrictions.)

**Comment by jcoyne** [comment]
Blocked by https://github.com/projectblacklight/arclight/pull/1252
