### ISSUE TITLE
Create record in ArchivesSpace for NTA

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#27]

**Comment by marlo-longley** [comment]
Ideally we could create a Collection, with our 2 series, and 1 or 2 items in each series. Simply for testing out the data structure.

**Comment by laurensorensen** [comment]
Here is a first run (with a lot of errors upon upload - XML validates when Spec custom text is commented out) 
https://drive.google.com/file/d/1rcORMPxqHYtbhqhO_jcjnsKsFlAS6Xyc/view?usp=sharing

**Comment by marlo-longley** [comment]
It will probably be best to link up and talk but in case it's helpful, here's a link to the version of your file that I edited

In case it's helpful, here's a link to my edited XML file
https://drive.google.com/file/d/16ubCaI5tboNNzMcqzT4DumsAAy3Mrf-V/view?usp=sharing

**Comment by laurensorensen** [comment]
Found today in re-creating the Collection for uploading a sample spreadsheet that we can edit in the collection level data the Spec Collection information! Screenshot: https://drive.google.com/file/d/1sFhNPiXO067JTeD3xUgu3GMO7quRYVRM/view?usp=sharing

**Comment by laurensorensen** [comment]
New collection is here: http://spec-as-stage.stanford.edu:8080/resources/10208#tree::resource_10208

**Comment by laurensorensen** [comment]
I tried uploading a big mapping of 397 items and 1 series (Document Books) and got this error over and over for each row (Hannah David and Franz discussed using the PURL as the EAD ID). 

It's confusing because the EAD ID does match the one in the form. 

"No Archival Object created
Row 83
Row 83 will not be processed due to errors: Form's EAD ID [https://purl.stanford.edu/mt839rq8746] does not match row's EAD ID [https://purl.stanford.edu/mt839rq8823]"

**Comment by laurensorensen** [comment]
Put the spreadsheet uploader mapping (using Document Books) here: 
https://drive.google.com/drive/folders/1hMepJUQI_tGiJ8ihfjniWTddAKI2ND9T?usp=sharing

And the broken down datasets here (by dc:type): 
https://drive.google.com/drive/folders/1zak25PXnKzYzt2o_kXYNeSBco0Se_hx5?usp=sharing

Took me a lot longer than I thought to break those down, but hopefully won't have to finagle with this anymore. Though there will have to be a certain amount of data manipulation (see other sheets (2 and 3?) within the Document Books.xlsx Excel doc for examples). 

Here are the other spreadsheet uploaders available from ArchivesSpace, don't know if that helps us: 
https://github.com/archivesspace/archivesspace/tree/master/templates

And the spreadsheet uploader tool training doc: 
https://docs.google.com/presentation/d/1xnaDi_ThF2heUF81-A0rJcN0U2EUQJ8yjK9nahR5xuA/edit#slide=id.p

**Comment by marlo-longley** [comment]
This is working in a draft form. @laurensorensen was able to ingest the ICJ data into ASpace using the uploader without errors.
Closing in favor of tracking more granular issues as they come up.
