### ISSUE TITLE
Discover how to get data out of ArchivesSpace

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#28]
1. Pick a non-NTA collection that's already in AS
2. Try to get EAD out -- do we download it as XML, is there an API endpoint? Which is preferable?

**Comment by marlo-longley** [comment]
http://spec-as-stage.stanford.edu:8080/
see NTA slack channel for credentials

**Comment by marlo-longley** [comment]
Thanks to @thatbudakguy for pointing out [this video from SUNY Albany](https://www.youtube.com/watch?v=WHNBKJCg-eI)
Helpful architecture screen grab:


![Image](https://user-images.githubusercontent.com/1328900/194940464-b925226b-2333-4570-93b8-a8d3c2adbfb0.png)

**Comment by thatbudakguy** [comment]
some of the scripts mentioned in that screenshot are in this repository:
https://github.com/UAlbanyArchives/aspacemigration

**Comment by marlo-longley** [comment]
For staging ASpace, how to use the API:

1. After authenticating and getting a session token in the JSON response of this command
`curl -s -F password="<pass>" "http://spec-as-stage.stanford.edu:8080/users/<username>/login"`

2. Run the following:
curl -H "X-ArchivesSpace-Session: <TOKEN>" \
"http://spec-as-stage.stanford.edu:8089/repositories/2/resource_descriptions/5687.xml?include_unpublished=false&include_daos=true&numbered_cs=true&print_pdf=false&ead3=false" //
--output ead.xml

This is using an arbitrary collection from the staging server. See this documentation: https://archivesspace.github.io/tech-docs/api/

**Comment by marlo-longley** [comment]
Closing as we've now finished discovery on this. We're moving on to more concrete tickets like #39.
