### ISSUE TITLE
Decide on parent container naming and grouping strategy

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/nta-arclight#30]
Related to #3 but I think it would be helpful to have a ticket that explicitly requires a decision to be made about our content inventory strategy. Specifically, we need to decide:

- Will we group all of the boxes and all of the electrical transcription content into two distinct parent containers?
- If not, will we use another parent container grouping strategy, or go with a completely flat organization (i.e., a single list of 28 boxes followed by _N_ number of days of electrical transcription content)?
- If so, what do we want to name the two parent containers? As shown below my suggestion is to use "Series 1: Paper material" (though we can try to come up with a better label than "Paper material") and "Series 2: Electronic media".
- If we use "Series" for these parent container labels, is it okay that we're using this archival term in this way? And can we generate minimal metadata necessary to support it (perhaps just a brief description to say it contains the 28 boxes, or the electrical transcriptions organized by day)?

Example of how the content inventory using this suggestion would look:

<img width="326" alt="inventory-one" src="https://user-images.githubusercontent.com/101482/194659074-2b11b559-aaec-4ee6-8aa8-25dff7568c28.png">

---

<img width="326" alt="inventory-two" src="https://user-images.githubusercontent.com/101482/194659216-dac555ca-69aa-4a09-8d98-df1732daa1f7.png">

---

<img width="326" alt="inventory-three" src="https://user-images.githubusercontent.com/101482/194659242-60673c2d-7e8b-438e-9234-7bb12fbfbc71.png">

---

A secondary question is the exact format of the display labels for the child components. I the examples above, I used "Box X:" plus the range of item numbers in that box, which will be more informative for users than simply "Box X". But if that is problematic for some reason we could simply use the Box number and the date like so (ignore the colon after the box labels in this example):

<img width="336" alt="Screen Shot 2022-10-07 at 2 34 49 PM" src="https://user-images.githubusercontent.com/101482/194661159-011d80e2-13ee-43e6-a698-b970266204a1.png">

**Comment by laurensorensen** [comment]
Thanks for this Gary! I've put some preliminary answers below (still need to look up a few things, and will update here as analysis proceeds): 

_- Will we group all of the boxes and all of the electrical transcription content into two distinct parent containers?_

My impression from our team discussions so far and feedback from CHRIJ and Regina (SUL curator) is that yes, this is the way to go. It also allows us to use something unique to Arclight, which is ability to represent "original order" by showing users the boxes in their original state and discs by day.  

_- If not, will we use another parent container grouping strategy, or go with a completely flat organization (i.e., a single list of 28 boxes followed by N number of days of electrical transcription content)?_

See above.

_- If so, what do we want to name the two parent containers? As shown below my suggestion is to use "Series 1: Paper material" (though we can try to come up with a better label than "Paper material") and "Series 2: Electronic media"._

Boxes include film too, so it could be Series: Paper and Film. I will do some more investigating about this this week, to see if there are archival content or cataloging standards for entering Series titles in EAD. 

- If we use "Series" for these parent container labels, is it okay that we're using this archival term in this way? And can we generate minimal metadata necessary to support it (perhaps just a brief description to say it contains the 28 boxes, or the electrical transcriptions organized by day)?_ 

For Series, yes I think it's appropriate bc Collection is the parent to Series in EAD. I do need to look up formatting for title and will follow up here when I get an answer about that. I am pretty sure I'll have time to do entering of the minimal metadata, esp if I can repeat it in the spreadsheet we'll use to upload to ASpace. There are just those "required" fields in EAD that I need to look into based on if we're using Series, Sub-series, Folder, etc. 

_A secondary question is the exact format of the display labels for the child components. I the examples above, I used "Box X:" plus the range of item numbers in that box, which will be more informative for users than simply "Box X". But if that is problematic for some reason we could simply use the Box number and the date like so (ignore the colon after the box labels in this example):_

I personally like having the Box 1: H-234-H456 - gives the user more to look at / refer back to. I imagine the uploader for ASpace has a way to merge two fields, will confirm.

**Comment by laurensorensen** [comment]
Another option here is using data from Column Q (date), plus Column format and and associated that with Box (aka Sub-series) title. So for example: Box 1: January 1, 1945-January 8, 1945. Might be more meaningful than the identifiers for researchers? 

dc: type also carries only one or two unique value per box, so could make sense for the title on that level to be: Box 9: Trial briefs, Document books, H-####-H-##### **(<-- worth noting with this example there are no dates associated with these druids. So it might make sense to have more than just the box number and date and identifier, so there's a little more for the researcher to go on).**

**Comment by marlo-longley** [comment]
+1 for the Box 1: H-234 to H-456 format
The H-### seems like a grounding reference point for researchers that may be easier to quickly comprehend than reading a date

**Comment by laurensorensen** [comment]
Adding to this ticket a few example titles from "box" levels from Duke's collection and from SUL EAD that Dinah provided (SUL in separate comment): 

From: https://archives.lib.duke.edu/catalog/wwiiprop
Deutscher Fichte-Bund press releases, issued by Theodor Kessemeier (in English), 1930s-1940s
**Important seeming note:** 
On the sidebar, the "navigate the collection" area doesn't have links to JUST one box. They appear to have links to children of boxes?? E.g. Deutscher Fichte-Bund press releases, issued by Theodor Kessemeier (in English), 1930s-1940s is in Box 1, expressed with "container" when you click through that title. So that title doesn't refer to the Box but to some other level..?

**Comment by marlo-longley** [comment]
@laurensorensen conducted a ton of analysis to generate these [diagrams](https://docs.google.com/spreadsheets/d/1Xz0hq28tyhESPTAcpowhlhw8JHNUManDWjP3hXZDkPg/edit#gid=1453131742) and [content counts](https://docs.google.com/spreadsheets/d/1Xz0hq28tyhESPTAcpowhlhw8JHNUManDWjP3hXZDkPg/edit#gid=0).

After discussion with @ggeisler we landed on the following so can close this ticket! 
<img width="674" alt="Screen Shot 2022-10-20 at 14 22 51" src="https://user-images.githubusercontent.com/1328900/197029329-16323f17-4e56-4beb-a976-7cfc6627b7e9.png">

Thanks for all the thought and effort here.
