### ISSUE TITLE
Update application title

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/nta-arclight#33]
Replace the current placeholder title in the application with `Taube Archive of the International Military Tribunal (IMT) at Nuremberg (1945-1946)`

Resulting masthead (in terms of the title; this example includes other unimplemented updates) should look something like:

<img width="1008" alt="194666425-937bed89-9327-4fef-bacf-baf2d6e5930a" src="https://user-images.githubusercontent.com/101482/194923216-bb3bba1b-146b-4ed1-ae57-3f0ab8917144.png">

**Comment by marlo-longley** [comment]
Collection title in EAD will likely be same as app title/masthead.
