### ISSUE TITLE
Decide if/how we will display repository information

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#36]
Currently we are test cataloging under the SPECCOLL repository in ASpace.
Obviously they don't hold the NTA collection. Can we create a new repository for NTA? We should ask Michael or someone who has that authority.

If not, we may have to write code that edits the repository data in the EAD once it's returned from the API.

Implications for #28

**Comment by laurensorensen** [comment]
Ah sorry missed this before - put this in a different ticket, but I found out today that the Repository fields are totally editable on the ASpace UI and at the collection level. Still a lot of errors to figure out from the uploader but at least the Repository field we shouldn't have to worry about!

**Comment by laurensorensen** [comment]
Here you go: https://github.com/sul-dlss/nta-arclight/issues/27#issuecomment-1279841546

**Comment by laurensorensen** [comment]
Oh sorry you found it already! Yes, it would be good to test and confirm to see if the edits exist in the XML.

**Comment by marlo-longley** [comment]
@laurensorensen I am getting back the following XML:

```
      <repository>
        <corpname>Department of Special Collections and University Archives</corpname>
      </repository>
```

**Comment by laurensorensen** [comment]
Franz mentioned to Hannah there is a work around for the repository naming issue (they made another instance of ASpace for Brenner Library and had to do this same workaround). 

Hannah still uncertain about what to call the repository, but I can follow up with her soon. 

I'll email Franz and ask about logistics for the work around.

**Comment by laurensorensen** [comment]
Getting a log-in for ASpace prod server so I can look up examples and download XML. Franz sent an example of the repository workaround but it's a link to OAC.. so going to look up the record in prod ASpace
His email: 

The workaround we used is actually pretty clumsy. We published a map collection under our "Rare Books Division" instance: 
https://oac.cdlib.org/findaid/ark:/13030/kt787007h3/
However, the front matter to the guide can be edited to clarify which library to contact, etc.
Franz

**Comment by laurensorensen** [comment]
Here is a link to the EAD XML from the above collection: https://drive.google.com/file/d/1W5gsnJnZa9y90M4G41a1mc9FYfl9hiyJ/view?usp=sharing

And info to access prod server on ASpace is user: lsorens pass: changeme

**Comment by marlo-longley** [comment]
Goal: if we are going to display repository, we want it to display something specific about NTA.

Next step is to discover what we want this view to look like. Consult with Gary about UX and work backwards.

**Comment by marlo-longley** [comment]
I'm closing this in favor of https://github.com/sul-dlss/nta-arclight/issues/57

First we need to decide what we want to display. Then we can figure out how to get the data to comply.
