### ISSUE TITLE
create VMs for stage, prod (sprint 0)

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#5]
I think dev and prod should be sufficient, but this could use analysis or discussion.
We don't yet know how we will be deploying the app/product

**Comment by marlo-longley** [comment]
The convention we will use is: stage, prod.

**Comment by thatbudakguy** [comment]
nope, I haven't made one yet — will do it today!

**Comment by thatbudakguy** [comment]
https://github.com/sul-dlss/operations-tasks/issues/3172

**Comment by marlo-longley** [comment]
@thatbudakguy thank you for writing this all up so thoroughly!
