### ISSUE TITLE
Decide about URL and possible landing page

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/nta-arclight#54]
[In LDCY meeting](https://docs.google.com/document/d/1FozA-t3_XMDyy6GtypY3lDNGlDV629DLnCxCFgszzuo/edit), VT stakeholders expressed interest in virtualtribunals.stanford.edu as the URL we would go with for having a landing page farther in the future. 

10/20/22 during workcycle, devs and ops assigned nta.stanford.edu and Hannah and myself expressed that it would need to be something other than this given that Tom expressed that more collections could be added later on. 

virtualtribunals.stanford.edu would be the natural choice but since Spotlight was used for the other exhibit, we would need links out via a landing page to VT in Spotlight and NTA in Arclight (which would be something like virtualtribunals.stanford.edu/nuremberg and then a redirect to VT exhibits in Spotlight) 

Would it be out of the scope and impossible given timeline to change the URL to virtualtribunals.stanford.edu and create a landing page to go with it (same SUL branding, etc)? Idea is that there would be two images with text underneath explaining the different collections briefly and the overall project name in a header plus text below the header that explains the overall project.

**Comment by marlo-longley** [comment]
Closing; duplicate in #56
