### ISSUE TITLE
Landing page and URL question

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/nta-arclight#56]
Earlier this week, Hannah messaged me that "nta.stanford.edu" won't work if we want to add collections later on down the line to Arclight. As a result, we had a conversation in our demo/retro (the part with stakeholders there) where we suggested the following: 
1. Use virtualtribunals.stanford.edu as the URL
2. Have that URL go to a landing page which in some manner points to Spotlight collections and Arclight collection (perhaps with other contextual information about the whole VT project). 
3. virtualtribunals.stanford.edu/nuremberg would be the URL for NTA

Penelope (runs CHRIJ) and Regina (SUL bibliographer) were good with this proposal, but I told them we would need to check with @ggeisler once he's back from vacation to see if it's possible within the scope of time we have.

Hannah suggested that I put together a formal proposal after @ggeisler takes a look and we get the ok to move forward from dev team. The proposal should go to Hannah, Tom, Penelope, David. I wonder though if this is needed since we got Penelope's OK. I will find out if it seems like something we should move forward with.

**Comment by marlo-longley** [comment]
Proposal: use vt.stanford.edu/nta, and add a landing page for VT pointing to NTA
Questions: what stack/technology is at vt.stanford.edu, is it part of Arclight instance or something else?

**Comment by laurensorensen** [comment]
Tom and Mike approved the URL plan as proposed, page one of Gary's visual design proposal: 
https://www.figma.com/proto/2ekjawwMTunlAesPyzIgpJ/NTA-%2F-Virtual-Tribunals-strategy?node-id=1727%3A20225&scaling=min-zoom&page-id=866%3A53780&starting-point-node-id=1727%3A20225

**Comment by marlo-longley** [comment]
Great! I think we can close in favor of:
#122 
#135
