### ISSUE TITLE
Decide on repository display

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#57]
**Will we display the index and show pages for repositories?** 
Currently the [landing page/route of this application](https://github.com/sul-dlss/nta-arclight/blob/1c0f36ba1d0be5efa5f1728f17bf62ac278428f1/config/routes.rb#L7) is the `repositories#index` page: (note this is a sample index and we will only have NTA/VT data in reality)

<img width="1686" alt="Screen Shot 2022-10-21 at 17 36 15" src="https://user-images.githubusercontent.com/1328900/197292477-44edfc19-5811-4f3c-b9e5-206d75f550c7.png">

The `#repositories#show` pages look like this:
<img width="1671" alt="Screen Shot 2022-10-21 at 17 36 48" src="https://user-images.githubusercontent.com/1328900/197292635-fe270e81-2871-472a-b1a5-141bd80ba0e8.png">

And repository is also prominent in the breadcrumbs
<img width="463" alt="Screen Shot 2022-10-21 at 17 39 14" src="https://user-images.githubusercontent.com/1328900/197292820-db50b7fe-f76e-4596-b089-ade9814eee0a.png">

- If we chose to display the repository structure, what text/content will we use?
- If we want to visually suppress repository, what are the technical implications?

**Comment by ggeisler** [comment]
@marlo-longley 

> Will we display the index and show pages for repositories?

No. See #77 for some explanation.

It's possible that we would want to display these repository pages in the future (if we added one or more collections from different repositories), but not anytime soon and definitely not for this workcycle's version of the site.

**Comment by marlo-longley** [comment]
Fixed by
https://github.com/sul-dlss/nta-arclight/pull/88
https://github.com/sul-dlss/nta-arclight/pull/87
