### ISSUE TITLE
dockerize nta-arclight

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#6]
[BL docker-compose](https://github.com/projectblacklight/blacklight/blob/main/docker-compose.yml)

[BL rake task for server ](https://github.com/projectblacklight/blacklight/blob/c2489126b2311a833d956ffbd5b70fd599a0ae75/tasks/blacklight.rake#L47)

**Comment by marlo-longley** [comment]
For Gary and others, must make sure we can still run locally without docker

**Comment by thatbudakguy** [comment]
fyi, it looks like Duke already containerized their fork: https://gitlab.oit.duke.edu/dul-its/dul-arclight/-/blob/main/Dockerfile

maybe we can compare this to the version in Blacklight and decide what we want to take from each.

**Comment by thatbudakguy** [comment]
@marlo-longley for clarity: does this ticket refer to dockerizing Arclight, or our own NTA Arclight? (or both?)

**Comment by marlo-longley** [comment]
@marlo-longley I suppose that's up for discussion but Duke's approach of containerizing their rails app (so that'd be NTA Arclight for us) seems more relevant to how we'd deploy, which @jcoyne mentioned yesterday in our Slack.
The Blacklight approach of spinning up a rails app with the engine included in a `docker-compose` seems more for dev purposes.

**Comment by jcoyne** [comment]
This is blocked by #1
