### ISSUE TITLE
Customize content and styling of topbar

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/nta-arclight#66]
For NTA, we want to change the height and colors of default topbar and add a Feedback link to it:

<img width="1010" alt="Screen Shot 2022-10-24 at 2 09 42 PM" src="https://user-images.githubusercontent.com/101482/197633142-198d155e-cf41-41a0-8751-4c48cd9c4f07.png">

## Styling of the topbar
- I suggest using the exact height (`35px`) and background color (`#8c1515`) currently used in Exhibits.
- Font color (`#fff`) and size (`0.9375rem`) same as Exhibits.

## Contents of the topbar
- **A:** Replace the "ArcLight" logo text with the SUL logo image - same version used in Exhibits. This should be linked to go to `https://library.stanford.edu/` (which is different than Exhibits).
- **B:** Retain the Bookmarks, History, and locale select menu we get from the core version of ArcLight.
- **C:** Add a "Feedback" link. I'll create a separate ticket for this because this might need some discussion and details about the form this link would trigger. EDIT: see #129.

**Comment by jcoyne** [comment]
@ggeisler @marlo-longley We can't offer bookmarks unless we also create a users table. Is this something we definitely want to do?  If so can we create a new ticket that specifies what types of authentication we want to provided?  We would also need to create a cron task to prune stale guest users if we want to offer that.

**Comment by ggeisler** [comment]
@jcoyne Are you talking about persistent bookmarks? I think we might want to enable those in the longer-run, since this is expected to be a site used heavily by serious researchers who might return to the site over time. But my assumption with the suggestion to retain the Bookmark feature was we would just be relying on the version we inherit from Blacklight, that exists in core ArcLight, and in a future version of NTA we could look at enhancing that by adding authentication (which by then we might want in order to support other features as well).

**Comment by jcoyne** [comment]
@ggeisler yes, the persistent bookmarks. Bookmarks require persistent users, so we need to decide on which auth mechanisms to support.

**Comment by marlo-longley** [comment]
@ggeisler if you agree, I think we can close this as #129 (part C in this mockup) and #134 (part A) are covering the remaining smaller tasks.

**Comment by ggeisler** [comment]
@marlo-longley Sure, sounds good.
