### ISSUE TITLE
Decide on datastore solution for source data

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#7]
We should not be using Solr as a stable data store. What is the latest good version of our source data / where does it live?
As simple as a CSV in a repository?

**Comment by marlo-longley** [comment]
We need to confirm that the metadata in SDR is identical to the spreadsheet in order to move forward with SDR as datastore

**Comment by laurensorensen** [comment]
I started on this analysis but haven't yet finished: https://docs.google.com/spreadsheets/d/18v_eurl9AVKk1VrZ1HtmxH1_8p76fVo6y-XGR0PwzGw/edit#gid=0

Enough there for our discussion, hopefully!

**Comment by laurensorensen** [comment]
**Summary:** 
Where I ended up with this on 9/19 is that the data of record coming into Arclight should come from SDR, but still unclear about how to do this in Cocina, and if there's any help we can get from scripting. 
Additionally, some individual fields from the original data from ICJ needs to be added to Cocina/SDR, as well as the structuring metadata for "box" and "day" from our [metadata model](https://docs.google.com/drawings/d/1TkSHjtiDUg5XlccS1GAp5C5NOOxFW9BYSC-8uQC8PBY/edit)

**Describing [the Analysis spreadsheet: ](https://docs.google.com/spreadsheets/d/18v_eurl9AVKk1VrZ1HtmxH1_8p76fVo6y-XGR0PwzGw/edit#gid=0) The crosswalk is in the first tab,** and that goes field-by-field indicating what is already in the Cocina spreadsheet in SDR for Media and separately for Documents. These were accessioned at different periods of time and do not have the same metadata included. In the left columns are the fields for Media and Document in current Cocina form, and to the right is if the field exists in the [original ICJ spreadsheet](https://docs.google.com/spreadsheets/d/1loytZIXYMuUajCkJRi3CyiqROMOARbhv/edit#gid=360187303) and any relevant notes (e.g. this field needs to be added for Media, etc). Added field means the data in this field is outside what was included by ICJ original spreadsheet. 

Cocina CSV for Media downloaded from Bulk Action > Download descriptive metadata here [https://argo.stanford.edu/catalog?f%5Bcontent_type_ssim%5D%5B%5D=media&f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+Nuremberg+trial+archives](https://www.google.com/url?q=https://argo.stanford.edu/catalog?f%255Bcontent_type_ssim%255D%255B%255D%3Dmedia%26f%255Bexploded_tag_ssim%255D%255B%255D%3DProject%2B%253A%2BNuremberg%2Btrial%2Barchives&sa=D&source=editors&ust=1663639535466757&usg=AOvVaw0ZjIOrFFoo6S49N02n_C7N)

Cocina CSV for Documents downloaded from Bulk Action > Download descriptive metadata here: [https://argo.stanford.edu/catalog?f%5Bcontent_type_ssim%5D%5B%5D=document&f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+Nuremberg+trial+archives](https://www.google.com/url?q=https://argo.stanford.edu/catalog?f%255Bcontent_type_ssim%255D%255B%255D%3Ddocument%26f%255Bexploded_tag_ssim%255D%255B%255D%3DProject%2B%253A%2BNuremberg%2Btrial%2Barchives&sa=D&source=editors&ust=1663639507923993&usg=AOvVaw2JDE91JKSYVVLL8OjXXYnT)

**The [second tab in the spreadsheet](https://docs.google.com/spreadsheets/d/18v_eurl9AVKk1VrZ1HtmxH1_8p76fVo6y-XGR0PwzGw/edit#gid=128514017)** describes changes that should be made to SDR metadata, for Documents, Media and Structural metadata like adding "box" or "day" as groupings, and summarizing the fields that are missing from first tab. 

We asked for examples from Arcadia about SDR "sub-records" and she sent examples which appear to not have their own druids (which NTA will). Downloading the Cocina spreadsheets for these, it seems like each resource under a Box would be relatedResource or relatedResource.adminMetadata. 

Followed up with Arcadia 9/19 to ask about the procedure for including items under a "box" or "day" that include druids to align with our metadata model: https://docs.google.com/drawings/d/1TkSHjtiDUg5XlccS1GAp5C5NOOxFW9BYSC-8uQC8PBY/edit

Still working on the first tab to clean up and crosswalk for note#.value, and others at the bottom of the page. But thought it was good to get this out ASAP. I'll update this ticket as I proceed with the crosswalk and hear back from Arcadia.

**Comment by laurensorensen** [comment]
Arcadia followed up to say we can have druids as "children" in the parent>child structure using virtual objects. 

Here are consul pages about it: 
https://consul.stanford.edu/display/DIGMETADATA/Preparing+and+describing+virtual+objects
https://consul.stanford.edu/display/DIGMETADATA/Virtual+object+and+combinator+FAQ

**Comment by laurensorensen** [comment]
I was wrong above about sub-records - they are different than virtual objects. I edited the analysis above to reflect that. 

Example Virtual object - **parent**: https://argo.stanford.edu/view/druid:pm947hz3258
Example Virtual object - **child of the above**: https://argo.stanford.edu/view/druid:sn076wc5449

**Comment by laurensorensen** [comment]
Another thing to consider is that in our check-in last week, Tom said to leave Arclight software open for potentially other collections to come in. So we might want to just map the NTA box>item day>item parent>child to EAD after all? To be consistent with other data that might come later that follows EAD structure?

**Comment by marlo-longley** [comment]
@laurensorensen I'm closing this! We decided to use ArchivesSpace to generate EAD and are storing a copy of that file in our Github repository.
