### ISSUE TITLE
Remove "Start over" and "Back to search" buttons from non-results pages

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/nta-arclight#84]
It looks like in NTA we're displaying the "Start over" and "Back to search" buttons on not just the search results pages but also the component pages:

<img width="1180" alt="Screen Shot 2022-10-26 at 10 09 29 AM" src="https://user-images.githubusercontent.com/101482/198094979-8f8dcec7-1bdb-4ce2-a797-b422b5bd4a50.png">

This doesn't seem to happen in core ArcLight. Core ArcLight is the desired pattern - we only want those buttons to display on the search results page.

**Comment by jcoyne** [comment]
<img width="1183" alt="Screenshot 2022-10-26 at 2 53 38 PM" src="https://user-images.githubusercontent.com/92044/198123504-fd1ac66f-987e-4979-a251-502fea6c1e9b.png">

Gary, I believe this is typical of all blacklight sites.  See an example from the demo

**Comment by ggeisler** [comment]
@jcoyne Sure, that might be the Blacklight default but Blacklight doesn't really have the concept of arriving at a show page from something that isn't a search result. In ArcLight and NTA the user might arrive at a show page by navigating through the content inventory (collection contents tree), so the Start Over and Back to Search buttons don't make a lot of sense (the user might not have ever done a search, but we're offering to take them back to it). They also take up vertical space on what is often a long page.

We don't show the buttons on a Spotlight show page because it has the same possibility of the user arriving at a show page from somewhere other than search (e.g., a link in a feature page):

<img width="1001" alt="Screen Shot 2022-10-26 at 1 56 43 PM" src="https://user-images.githubusercontent.com/101482/198136122-9bc7d5f6-1d0b-4084-a759-10e1c076283e.png">

---

And for some reason I get a different view of a show page in vanilla ArcLight, where I don't see those buttons:

<img width="1238" alt="Screen Shot 2022-10-26 at 1 47 23 PM" src="https://user-images.githubusercontent.com/101482/198135557-8d5340c1-07c6-4c55-8cbe-b33a7de5c8a3.png">

**Comment by jcoyne** [comment]
It looks to me like you never see those controls unless you have a current search session.   If you delete your session cookie, you will see those buttons disappear.

**Comment by jcoyne** [comment]
Ah, it looks like we just hide these controls in exhibits.

https://github.com/sul-dlss/exhibits/blob/b52e00e744dec65e7e290a8987886bd52be01a54/app/assets/stylesheets/modules/blacklight_overrides.scss#L35-L37

We can do that here if you are okay with changing "we only want those buttons to display on the search results page." to "we never want these buttons to display"

**Comment by ggeisler** [comment]
We do show the Start over button on search results pages in Exhibits, so I guess I don't understand why it has to be all or nothing:

<img width="1001" alt="Screen Shot 2022-10-26 at 2 23 11 PM" src="https://user-images.githubusercontent.com/101482/198141638-72ae20a4-4a27-4b61-b92c-9b95ecc384c1.png">

---

And I haven't had a chance to post a ticket about NTA search results yet but my intention for the results page in NTA is to display just the Start over button, not the Back to Search button (so for that one, yes, we never want to show it):

<img width="1001" alt="Screen Shot 2022-10-26 at 2 25 19 PM" src="https://user-images.githubusercontent.com/101482/198142023-413d4042-14c8-4854-bc9e-60c9e8ef903b.png">

--- 

I guess this is an opinionated change but I'm suggesting it for NTA not ArcLight, so we're not changing things at the core ArcLight level (though I believe Duke at least has followed the same pattern I'm suggesting so I'm not sure that others might not want the same approach).

**Comment by jcoyne** [comment]
I'm trying to understand how it's done elsewhere, because I don't know how to make such a change only on search result pages and not component pages. As far as blacklight/arclight is concerned, they are the same.

**Comment by jcoyne** [comment]
@ggeisler I think we are talking about different things.  I am talking about hiding it always on the show page whether or not you are in a "search context" a search context is when you are viewing a search result but click the "next" button.  But then you want to go back and start over.

**Comment by ggeisler** [comment]
@jcoyne Okay, then yes, always hide those elements on the show/component page whether or not you are in a search context. When you are on a show page, the very top of the main content area should always start with the breadcrumb, no matter how you got to that show/component page.

On a search results page, we'd like to show the Start over button, but not the Back to Search button, as shown in my NTA mockup above.
