### ISSUE TITLE
Spec out an example EAD format for NTA data

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/nta-arclight#9]
Let's get a basic example with a few boxes and items, and then see what it would take to script our CSV into that format.

**Comment by laurensorensen** [comment]
I wrote a very basic EAD document without all the fields from previous CSV analysis (can't attach XML to comments here, says Github!), name is sample_ead.xml and the others in this drive folder are from Dinah from ArchivesSpace, and again don't necessarily include all the fields we'll need for NTA: https://drive.google.com/drive/folders/1hDMus2lrXIKzAU8ejjVKgQhPDNDflq2w?usp=sharing

**Comment by marlo-longley** [comment]
Closing now that we are iterating within ArchivesSpace for the EAD.
See #27
