### ISSUE TITLE
What data from "Access" section is in EAD versus YAML? 

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/nta-arclight#92]
Discussion here: 
https://stanfordlib.slack.com/archives/C040NV8ENCQ/p1666821325469829

Can fields and data in the Access section be changed to accommodate the fact that SUL does not steward the physical material? Could we add a field to reference to SUL / CHRIJ stewarding the digital collection?

**Comment by marlo-longley** [comment]
Everything in the Access section comes from the YAML.
We added placeholder data about ICJ to test that we could change values directly in the repository.
We need to verify Location, Visit Note, Contact info.
<img width="641" alt="Screen Shot 2022-10-27 at 16 49 26" src="https://user-images.githubusercontent.com/1328900/198395167-f5b0d7fe-5457-41db-81e8-9585767102d7.png">

**Comment by laurensorensen** [comment]
I'd like to leave out "Before you visit" entirely. 

Is it possible to change "Before you visit" to:
Digital collection stewarded by: Stanford University Libraries (link: https://library.stanford.edu/) and Center for Human Rights and International Justice (link: https://humanrights.stanford.edu/) 

And change the order so that "Contact" is just under the "Location of This Collection" field?

**Comment by marlo-longley** [comment]
Closing as we did the discovery on this.
This request to change the fields is captured in #125
